//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GControlClient.GSrvRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GSrvRef.IGSrv")]
    public interface IGSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGSrv/PingStr", ReplyAction="http://tempuri.org/IGSrv/PingStrResponse")]
        string PingStr(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGSrv/PingStr", ReplyAction="http://tempuri.org/IGSrv/PingStrResponse")]
        System.Threading.Tasks.Task<string> PingStrAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGSrvChannel : GControlClient.GSrvRef.IGSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GSrvClient : System.ServiceModel.ClientBase<GControlClient.GSrvRef.IGSrv>, GControlClient.GSrvRef.IGSrv {
        
        public GSrvClient() {
        }
        
        public GSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PingStr(string str) {
            return base.Channel.PingStr(str);
        }
        
        public System.Threading.Tasks.Task<string> PingStrAsync(string str) {
            return base.Channel.PingStrAsync(str);
        }
    }
}
